#!/usr/bin/env python3
"""
sync_version.py
---------------
Reads the latest version from CHANGELOG.md and:
1. Writes it to Manuscript/version.tex
2. Automatically renames the main manuscript .tex and .pdf files
3. Replaces any hardcoded version strings inside the .tex files
4. Updates the Zenodo release script

Usage:
    python sync_version.py               # syncs everything
    python sync_version.py --print-only  # just prints the version
"""

import re
import sys
import os
import glob
import shutil

REPO_ROOT     = os.path.dirname(os.path.abspath(__file__))
CHANGELOG     = os.path.join(REPO_ROOT, "CHANGELOG.md")
VERSION_TEX   = os.path.join(REPO_ROOT, "Manuscript", "version.tex")
ZENODO_SCRIPT = os.path.join(REPO_ROOT, "Scripts", "Archive", "itsm_zenodo_release.py")

def extract_latest_version(changelog_path: str) -> str:
    pattern = re.compile(r"^##\s+Version\s+([\d.]+)", re.MULTILINE)
    with open(changelog_path, encoding="utf-8") as f:
        content = f.read()
    match = pattern.search(content)
    if not match:
        raise RuntimeError("No '## Version X.Y.Z' heading found in CHANGELOG.md")
    return "v" + match.group(1)

def write_version_tex(version: str, output_path: str) -> None:
    tex = (
        f"% Auto-generated by sync_version.py — do not edit manually.\n"
        f"% Source of truth: CHANGELOG.md\n"
        f"\\newcommand{{\\itsmVersion}}{{{version.replace('v', '')}}}\n"
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(tex)
    print(f"[sync_version] Wrote version {version} -> {os.path.basename(output_path)}")

def rename_manuscript_files(new_version: str):
    # Find ITSM_Core_Cosmology_v*.tex
    manuscript_dir = os.path.join(REPO_ROOT, "Manuscript")
    tex_files = glob.glob(os.path.join(manuscript_dir, "ITSM_Core_Cosmology_v*.tex"))
    
    for old_file in tex_files:
        # Extract old version from filename
        basename = os.path.basename(old_file)
        match = re.search(r"ITSM_Core_Cosmology_(v[\d.]+)\.tex", basename)
        if match:
            old_version = match.group(1)
            if old_version != new_version:
                new_basename = basename.replace(old_version, new_version)
                new_file = os.path.join(manuscript_dir, new_basename)
                shutil.move(old_file, new_file)
                print(f"[sync_version] Renamed {basename} -> {new_basename}")
                
                # Check for corresponding PDF
                old_pdf = old_file.replace(".tex", ".pdf")
                if os.path.exists(old_pdf):
                    new_pdf = new_file.replace(".tex", ".pdf")
                    shutil.move(old_pdf, new_pdf)
                    print(f"[sync_version] Renamed {os.path.basename(old_pdf)} -> {os.path.basename(new_pdf)}")
                
                # Clean up old LaTeX auxiliary files
                old_aux_pattern = os.path.join(manuscript_dir, f"ITSM_Core_Cosmology_{old_version}.*")
                for aux_file in glob.glob(old_aux_pattern):
                    if not aux_file.endswith(".tex") and not aux_file.endswith(".pdf"):
                        os.remove(aux_file)
                        print(f"[sync_version] Removed obsolete auxiliary file: {os.path.basename(aux_file)}")
            return old_version
    return None

def update_file_contents(file_path: str, old_version: str, new_version: str):
    if not os.path.exists(file_path):
        return
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    if old_version in content:
        new_content = content.replace(old_version, new_version)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"[sync_version] Updated internal version strings in {os.path.basename(file_path)}")

if __name__ == "__main__":
    new_version = extract_latest_version(CHANGELOG)
    if "--print-only" in sys.argv:
        print(new_version.replace('v', ''))
        sys.exit(0)
        
    write_version_tex(new_version, VERSION_TEX)
    old_version = rename_manuscript_files(new_version)
    
    if old_version and old_version != new_version:
        # Update strings in manuscript
        manuscript_dir = os.path.join(REPO_ROOT, "Manuscript")
        main_tex = os.path.join(manuscript_dir, f"ITSM_Core_Cosmology_{new_version}.tex")
        supp_tex = os.path.join(manuscript_dir, "Supplementary", "Supplementary.tex")
        
        update_file_contents(main_tex, old_version, new_version)
        update_file_contents(supp_tex, old_version, new_version)
        update_file_contents(ZENODO_SCRIPT, old_version, new_version)
