#!/usr/bin/env python3
"""
sync_version.py
---------------
Reads the latest version from CHANGELOG.md and writes it to
Manuscript/version.tex so that Main.tex always stays in sync
without manual editing.

Usage:
    python sync_version.py               # writes version.tex
    python sync_version.py --print-only  # just prints the version

Called automatically by run_all.py before LaTeX compilation.
"""

import re
import sys
import os

REPO_ROOT     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHANGELOG     = os.path.join(REPO_ROOT, "CHANGELOG.md")
VERSION_TEX   = os.path.join(REPO_ROOT, "Manuscript", "version.tex")

def extract_latest_version(changelog_path: str) -> str:
    """Return the version string from the first '## Version X.Y.Z' line."""
    pattern = re.compile(r"^##\s+Version\s+([\d.]+)", re.MULTILINE)
    with open(changelog_path, encoding="utf-8") as f:
        content = f.read()
    match = pattern.search(content)
    if not match:
        raise RuntimeError("No '## Version X.Y.Z' heading found in CHANGELOG.md")
    return match.group(1)

def write_version_tex(version: str, output_path: str) -> None:
    r"""Write a minimal .tex file defining \itsmVersion."""
    tex = (
        f"% Auto-generated by Scripts/sync_version.py — do not edit manually.\n"
        f"% Source of truth: CHANGELOG.md\n"
        f"\\newcommand{{\\itsmVersion}}{{{version}}}\n"
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(tex)
    print(f"[sync_version] Wrote version {version} -> {output_path}")

if __name__ == "__main__":
    version = extract_latest_version(CHANGELOG)
    if "--print-only" in sys.argv:
        print(version)
    else:
        write_version_tex(version, VERSION_TEX)
